runtime:
  device: cuda
  batch_size: 16
  save_every: 500
  progress_bar: true

paths:
  chexpert: ../mimicdst/mimic-cxr-2.0.0-chexpert.csv.gz
  metadata: ../mimicdst/mimic-cxr-2.0.0-metadata.csv.gz
  split: ../mimicdst/mimic-cxr-2.0.0-split.csv.gz
  images: ../mimicdst/P10_Samples
  notes: ./data/fake_notes
  output: ./results/final_mimic_visit_level.csv


filtering:
  require_any:
    - image
    - note

model:
  name: emilyalsentzer/Bio_ClinicalBERT
  max_length: 256
