paths:
  mimic_prepared_csv: ../gpu_base/results/final_mimic_visit_level.csv
  embedding_cm_csv: ../gpu_base/results/embedding_cm.csv
  chexpert: ../mimicdst/mimic-cxr-2.0.0-chexpert.csv.gz
  metadata: ../mimicdst/mimic-cxr-2.0.0-metadata.csv.gz
  split: ../mimicdst/mimic-cxr-2.0.0-split.csv.gz
  
  #images: ../mimicdst/P10_Samples
  #notes: ../mimicdst/P10_ClinicalNotes

  notes: /media/mohammad/Vir3/Agentic AI/Data/mimic-cxr-reports
  images: /media/mohammad/Vir3/Agentic AI/Data/physionet.org/files/mimic-cxr-jpg/2.1.0/files


  patients_features: ../mimicdst/mimic-dst-outcome/patients.csv.gz
  admissions_features: ../mimicdst/mimic-dst-outcome/admissions.csv.gz
  output_dir: ../gpu_base/results/
  output: ./results/final_mimic_visit_level.csv

  edstays: ../mimicdst/mimic-iv-ed-2.2/edstays.csv.gz
  triage: ../mimicdst/mimic-iv-ed-2.2/triage.csv.gz
  vitalsign: ../mimicdst/mimic-iv-ed-2.2/vitalsign.csv.gz
  pyxis: ../mimicdst/mimic-iv-ed-2.2/pyxis.csv.gz


runtime:
  device: gpu
  save_every: 500
  progress_bar: true

clinical_note:
  mode: real
  allow_missing: true

filtering:
  keep_if_missing_all: false
