paths:
  csv: ../cpu_base/results/final_mimic_visit_level.csv
  checkpoint: ./results/swin_dualview.pt
  cm_output: ./results/embedding_cm.csv

data:
  split_column: split
  train_split: train

  image_columns:
    frontal: path_img_fr
    lateral: path_img_la

  id_columns:
    subject_id: subject_id
    study_id: study_id

  label_columns:
    - Atelectasis
    - Cardiomegaly
    - Consolidation
    - Edema
    - Enlarged Cardiomediastinum
    - Fracture
    - Lung Lesion
    - Lung Opacity
    - Pleural Effusion
    - Pleural Other
    - Pneumonia
    - Pneumothorax
    - Support Devices

training:
  epochs: 5
  batch_size: 2
  lr: 1e-4
